# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckoutExampleObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 source 'https://github.com/Kount/kount-pod-spec.git'
  # Pods for CheckoutExampleObjC
  pod 'Kount','4.1.5'

end
